services:
  archiver:
    image: sharathchandra/swifey-archiver
    depends_on:
      - mongodb
      - redis
    restart: always
  http:
    build: ./http
    depends_on:
      - mongodb
    restart: always
  ws:
    build: ./ws
    depends_on:
      - mongodb
    restart: always
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: swifey
    ports:
      - 27017:27017
  redis:
    image: redis
    restart: always
networks:
  default:
    external:
      name: swifey
      driver: bridge
      attachable: true
      internal: true
      allow-non-internal: true
